name: Pre-commit for terraform

on:
  workflow_call:
    inputs:
      BOT_GITHUB_USERNAME:
        description: 'Username to allow fetching private modules on GitHub (BOT_GITHUB_TOKEN is required)'
        type: string
        required: false
    secrets:
      BOT_GITHUB_TOKEN:
        required: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write # required only when auto-commit is enabled
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Detect terraform version
        id: detect-terraform-version
        run: echo "terraform_version=$(cat .terraform-version)" >> "$GITHUB_OUTPUT"

      - name: Install tflint
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 # v6.2.1

      - name: Install checkov
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-checkov@v15.6.1

      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ steps.detect-terraform-version.outputs.terraform_version }}

      - name: Install terraform-docs
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-terraform-docs@v15.6.1

      - name: Setup authentication for private terraform modules
        if: env.BOT_GITHUB_USERNAME && env.BOT_GITHUB_TOKEN
        env:
          BOT_GITHUB_USERNAME: ${{ inputs.BOT_GITHUB_USERNAME }}
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          git config --global url."https://${BOT_GITHUB_USERNAME}:${BOT_GITHUB_TOKEN}@github.com".insteadOf "https://github.com"

      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v15.6.1
        with:
          auto-commit: "true" # optionally commit automated fix changes back
          skip_checkout: "false" # mandatory with auto-commit
